services:
  - type: web
    name: company-dashboard
    plan: free
    branch: master
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/CompanyDashBoard-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
